var fontList = [
    'Arial',
    "Acme",
    "Audiowide",
    "Aclonica",
    "arial black",
    "Aguafina Script",
    "Arima Madurai",
    "Allerta Stencil",
    "Abril Fatface",
    "Arizonia",
    'Brush Script MT',
    "Black And White Picture",
    "Black Ops One",
    "Big Shoulders Display",
    'Courier New,Courier',
    "cursive",
    "comic sans ms",
    "Creepster",
    "Caveat",
    "Charm",
    "Cabin Sketch",
    "Caveat Brush",
    "Cutive Mono",
    "Cinzel Decorative",
    "Damion",
    "Dancing Script",
    "Edu NSW ACT Foundation",
    "Fasthand",
    'Georgia',
    'Garamond',
    'Geneva',
    "Great Vibes",
    "Gajraj One",
    "Graduate",
    "Grenze Gotisch",
    "Geostar Fill",
    'Helvetica',
    "Impact",
    "IBM Plex Sans",
    "Julius Sans One",
    "Kaushan Script",
    "Kosugi Maru",
    "Knewave",
    "Lucida Console",
    "Lobster",
    "League Gothic",
    "Mogra",
    "monospace",
    "Monoton",
    "Nunito",
    "Nanum Gothic",
    "Oleo Script Swash Caps",
    "Poppins",
    "Pacifico",
    "Playball",
    "Permanent Marker",
    "Parisienne",
    "Pinyon Script",
    "Petit Formal Script",
    "Quicksand",
    "Rubik Iso",
    "Righteous",
    "Rancho",
    "Rye",
    "sans-serif",
    "Space Mono",
    "Sigmar One",
    "Six Caps",
    "Syncopate",
    "Stalemate",
    "Smokum",
    'tohoma',
    'Trebuchet MS',
    'Times New Roman',
    'Times',
    "trebuchet ms",
    "Unica One",
    "UnifrakturMaguntia",
    "verdana",
    'Verdana',
    "VT323",
    "Wallpoet",
    "Yatra One",
]

export default fontList;